from flask import Flask, render_template, request, jsonify, send_file
import json
import os

app = Flask(__name__, template_folder='templates', static_folder='static')

# صفحة تسجيل الدخول
@app.route('/')
def login():
    return render_template('login.html')

# لوحة التحكم الرئيسية
@app.route('/panel')
def panel():
    return render_template('panel.html')

# API لإدارة البث
@app.route('/api/streams', methods=['GET', 'POST', 'PUT', 'DELETE'])
def manage_streams():
    if request.method == 'GET':
        # عرض البثوث
        with open('/flussonic/config/streams.json', 'r') as f:
            streams = json.load(f)
        return jsonify(streams)
    
    elif request.method == 'POST':
        # إضافة بث جديد
        data = request.json
        # حفظ في ملف
        return jsonify({"success": True, "id": data.get("id")})
    
    elif request.method == 'PUT':
        # تعديل بث
        return jsonify({"success": True})
    
    elif request.method == 'DELETE':
        # حذف بث
        return jsonify({"success": True})

# إنشاء M3U
@app.route('/api/generate/m3u')
def generate_m3u():
    username = request.args.get('username')
    password = request.args.get('password')
    
    # إنشاء M3U
    m3u_content = "#EXTM3U\n# Generated by IPTV Panel\n"
    
    # إضافة بثوث
    return m3u_content, 200, {'Content-Type': 'audio/x-mpegurl'}

# معلومات النظام
@app.route('/api/system/stats')
def system_stats():
    return jsonify({
        "cpu": 10.5,
        "memory": 45.2,
        "streams": 25,
        "bandwidth": "1.2 Gbps"
    })

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000, debug=True)
